language: node_js
node_js:
- '0.10'
sudo: true
before_install:
- bundle install
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  email: false
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: labs-pivotal-ui@pivotal.io
  password:
    secure: NJtQlPaxEfDUEwPl49HQWtTL8LqErCxwK+fCPmC37ZVHMPHcfi8vQ2g3qZJvv73q783zKoZRdI/TzgI/8jqdzK1Djgf5dElz78C7/3NmiWkDh1Lomt93b+qEepyddVInNCVsYu1UBWS2aouY2Z+q4B74voqKJI46ROAAbxQ32dD5eYzHjfxL7RybLidgGXPHoFnRbvphpPGgbGtYBpGQEBcgRrnOOu96a8W1rl2QJ+MEpez2xSMUVT7BlrMNN0nqzSWjtdHFE6Ed7SCVwgy15PNARbl5w5bILWaR+HJ6HBTRb562c1SwcgB+Vtue4tsyPl+Orx6gZ9kqcIbRpYMQv5tQ3jAdgitNPnhMF+H+OedZA95Kz3GlBi8FjEPogYbLVmgi9ecoBSCtoCUVKQ9PHOBMYRInZj3PohxsPCd+jhyDu1il2CSRGz7xyjuS5ybRCD8hfHkl/n7XcqiJ24tW5WFYtXllVdwuh1tnrqJcrJPujeKcHR5AISy4iN8QRv5Myn/Nli/Oa5cEuNHyfIFcieviTuon9AmCVj51fx4Z8NLaf1Pei8BTyp3rNS2UBud7oQFEyTc5b+1zi/WDQ4ejZSSrMEyk/AJsGassJKceMX5E0cC6pKDaIBQglBoGPKeQ93DWwH9YhPbNMIiKm7EtWmra+cW3roO74vDd8lRA0co=
  organization: pivotal
  space: pivotal-ui
  on:
    repo: pivotal-cf/pivotal-ui
    branch: master
