groups:
- name: development
  jobs:
  - library-unit-test-development
  - react-styleguide-development
  - hologram-styleguide-development
  - hologram-styleguide-development-deploy

resources:
  - name: pivotal-ui-development
    type: git
    source:
      uri: git@github.com:pivotal-cf/pivotal-ui.git
      branch: development
      private_key: ((pui-ci-credentials/Notes/pivotal-ui-git-key))

jobs:
  - name: library-unit-test-development
    plan:
      - get: pivotal-ui-development
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pivotalui/concourse
              tag: v3
          inputs:
          - name: pivotal-ui-development
          run:
            path: bash
            args:
            - -exc
            - |
              cd pivotal-ui-development/library
              npm i
              gulp build
              gulp ci

  - name: hologram-styleguide-development
    plan:
      - get: pivotal-ui-development
        trigger: true
        passed: [library-unit-test-development]
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pivotalui/concourse
              tag: v3
          inputs:
          - name: pivotal-ui-development
          run:
            path: bash
            args:
            - -exc
            - |
              cd pivotal-ui-development/library
              npm i
              gulp build

              cd ../styleguide
              bundle
              npm i
              gulp styleguide-build
              gulp ci

  - name: react-styleguide-development
    plan:
      - get: pivotal-ui-development
        trigger: true
        passed: [library-unit-test-development]
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pivotalui/concourse
              tag: v3
          inputs:
          - name: pivotal-ui-development
          run:
            path: bash
            args:
            - -exc
            - |
              pivotal-ui-development/styleguide_new/bin/gemini-in-docker.sh pivotal-ui-development test

  - name: hologram-styleguide-development-deploy
    plan:
      - get: pivotal-ui-development
        trigger: true
        passed: [hologram-styleguide-development]
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pivotalui/concourse
              tag: v3
          params:
            CF_PASSWORD: ((pui-ci-credentials/Notes/pivotal-ui-cf-password))
          inputs:
          - name: pivotal-ui-development
          run:
            path: bash
            args:
            - -exc
            - |
              cd pivotal-ui-development/library
              npm i
              gulp build
              cd ../styleguide

              npm i
              bundle
              gulp styleguide-build
              cf api api.run.pivotal.io
              cf auth pivotal-ui@pivotal.io $CF_PASSWORD
              cf target -o pivotal -s pivotal-ui-staging
              cf push

  - name: react-styleguide-development-deploy
    plan:
      - get: pivotal-ui-development
        trigger: true
        passed: [react-styleguide-development]
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pivotalui/concourse
              tag: v3
          params:
            CF_PASSWORD: ((pui-ci-credentials/Notes/pivotal-ui-cf-password))
          inputs:
          - name: pivotal-ui-development
          run:
            path: bash
            args:
            - -exc
            - |
              cd pivotal-ui-development/library
              npm i
              gulp build
              cd ../styleguide_new
              ./bin/deploy.sh $CF_PASSWORD
