resources:
  - name: pivotal-ui-development
    type: git
    source:
      uri: git@github.com:pivotal-cf/pivotal-ui.git
      branch: development
      private_key: {{pivotal-ui-git-key}}
  - name: pivotal-ui-master
    type: git
    source:
      uri: git@github.com:pivotal-cf/pivotal-ui.git
      branch: master
      private_key: {{pivotal-ui-git-key}}

jobs:
  - name: library-master
    plan:
      - get: pivotal-ui-master
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pivotalui/concourse
              tag: v2
          inputs:
          - name: pivotal-ui-master
          run:
            path: bash
            args:
            - -exc
            - |
              cd pivotal-ui-master/library
              npm i
              gulp build
              gulp ci

  - name: styleguide-master
    plan:
      - get: pivotal-ui-master
        trigger: true
        passed: [library-master]
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pivotalui/concourse
              tag: v2
          inputs:
          - name: pivotal-ui-master
          run:
            path: bash
            args:
            - -exc
            - |
              cd pivotal-ui-master/library
              npm i
              gulp build

              cd ../styleguide
              bundle
              npm i
              gulp styleguide-build
              gulp ci

  - name: library-development
    plan:
      - get: pivotal-ui-development
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pivotalui/concourse
              tag: v2
          inputs:
          - name: pivotal-ui-development
          run:
            path: bash
            args:
            - -exc
            - |
              cd pivotal-ui-development/library
              npm i
              gulp build
              gulp ci

  - name: styleguide-development
    plan:
      - get: pivotal-ui-development
        trigger: true
        passed: [library-development]
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pivotalui/concourse
              tag: v2
          inputs:
          - name: pivotal-ui-development
          run:
            path: bash
            args:
            - -exc
            - |
              cd pivotal-ui-development/library
              npm i
              gulp build

              cd ../styleguide
              bundle
              npm i
              gulp styleguide-build
              gulp ci

  - name: styleguide-new-development
    plan:
      - get: pivotal-ui-development
        trigger: true
        passed: [library-development]
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pivotalui/concourse
              tag: v2
          inputs:
          - name: pivotal-ui-development
          run:
            path: bash
            args:
            - -exc
            - |
              service dbus restart
              xvfb-run chromedriver --port=4444 --url-base=wd/hub &

              cd pivotal-ui-development/library
              npm i
              gulp build

              cd ../styleguide_new
              npm i
              ./node_modules/.bin/webpack --config backend-webpack.config.babel.js
              ./node_modules/.bin/webpack --config frontend-webpack.config.babel.js
              npm run watch &

              sleep 10

              ./node_modules/.bin/gemini --reporter flat test

  - name: styleguide-development-deploy
    plan:
      - get: pivotal-ui-development
        trigger: true
        passed: [styleguide-development]
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pivotalui/concourse
              tag: v2
          params:
            CF_PASSWORD: {{pivotal-ui-cf-password}}
          inputs:
          - name: pivotal-ui-development
          run:
            path: bash
            args:
            - -exc
            - |
              cd pivotal-ui-development/library
              npm i
              gulp build
              cd ../styleguide

              npm i
              bundle
              gulp styleguide-build
              cf api api.run.pivotal.io
              cf auth pivotal-ui@pivotal.io $CF_PASSWORD
              cf target -o pivotal -s pivotal-ui-staging
              cf push

  - name: styleguide-new-development-deploy
    plan:
      - get: pivotal-ui-development
        trigger: true
        passed: [styleguide-new-development]
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pivotalui/concourse
              tag: v2
          params:
            CF_PASSWORD: {{pivotal-ui-cf-password}}
          inputs:
          - name: pivotal-ui-development
          run:
            path: bash
            args:
            - -exc
            - |
              cd pivotal-ui-development/library
              npm i
              gulp build
              cd ../styleguide_new
              ./bin/deploy.sh $CF_PASSWORD
