---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalui/concourse

inputs:
- name: pivotal-ui

run:
  path: pivotal-ui-development/concourse/tasks/hologram-styleguide/run.sh